# File .gitlab-ci.yml
image: maven:3.8.6-openjdk-18-slim

stages:
  - build
  - validate
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

validate:
  stage: validate
  script:
    - mvn validate
  #rules:
   # - if: '$CI_COMMIT_BRANCH =~ /^(Story|Task).*/'

test_and_generate_docs:
  stage: test
  script:
    - mvn test
    #- mvn javadoc:javadoc # Inserire istruzione per gen doc
 # rules:
 #   - if: '$CI_COMMIT_BRANCH =~ /^(Story|Task).*/ && $CI_COMMIT_REF_NAME =~ /^Sprint.*/'
  #  - if: '$CI_COMMIT_BRANCH == "main" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^Sprint.*/'

deploy:
  stage: deploy
  script:
    - mvn deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^Sprint.*/'
