# File .gitlab-ci.yml
image: maven:3.8.6-openjdk-18-slim

stages:
  - build
  - validate
  - test
  - deploy

services:
  - name: mysql:8.0
    alias: mysql
    command:
      - --default-authentication-plugin=mysql_native_password

variables:
  MYSQL_ROOT_PASSWORD: Grillo_00
  MYSQL_DATABASE: db_tin
  MYSQL_USER: springuser
  MYSQL_PASSWORD: Grillo_00
  MYSQL_HOST: mysql
  MYSQL_PORT: 3306
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_tin
  SPRING_DATASOURCE_USERNAME: springuser
  SPRING_DATASOURCE_PASSWORD: Grillo_00

connect:
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

before_script:
  - echo "Waiting for MySQL to be ready..."
  - apt-get install -y mysql
  - until mysql -h "$MYSQL_HOST" -u root -p"$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"; do echo "waiting for mysql"; sleep 1; done
  - mysql -h "$MYSQL_HOST" -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
  - mysql -h "$MYSQL_HOST" -u root -p"$MYSQL_ROOT_PASSWORD" -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
  - mysql -h "$MYSQL_HOST" -u root -p"$MYSQL_ROOT_PASSWORD" -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';"
  - mysql -h "$MYSQL_HOST" -u root -p"$MYSQL_ROOT_PASSWORD" -e "FLUSH PRIVILEGES;"

build:
  stage: build
  script:
    - mvn compile

validate:
  stage: validate
  script:
    - mvn validate
  #rules:
   # - if: '$CI_COMMIT_BRANCH =~ /^(Story|Task).*/'

test_and_generate_docs:
  stage: test
  script:
    - mvn test
    #- mvn javadoc:javadoc # Inserire istruzione per gen doc
 # rules:
 #   - if: '$CI_COMMIT_BRANCH =~ /^(Story|Task).*/ && $CI_COMMIT_REF_NAME =~ /^Sprint.*/'
  #  - if: '$CI_COMMIT_BRANCH == "main" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^Sprint.*/'

deploy:
  stage: deploy
  script:
    - mvn deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^Sprint.*/'
